# Generated by Django 2.2 on 2019-06-25 18:24

from django.db import migrations, models
import datetime
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160406_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(
                related_name='ingredients', to='menu.Ingredient'),
        ),
    ]
